### ISSUE TITLE
No module named GAN

### ISSUE THREAD

**Issue by finalyXG** [brownvc/ganimorph#2]
Hi,
when I try to run the main.py, it shows me that "No module named GAN" for code in the line below:

https://github.com/brownvc/ganimorph/blob/cf9433947af030912e1230224abf8b1a79f8060e/main.py#L21

is there any file/folder missing in the current version? 

Thanks a lot

**Comment by ssdutHB** [comment]
There is no file named GAN.

**Comment by finalyXG** [comment]
Yes, I think I see the problem, thanks.
