### ISSUE TITLE
Where is model.get_inputs_desc() defined? 

### ISSUE THREAD

**Issue by aasharma90** [brownvc/ganimorph#21]
Hi @Skylion007 , 

Thanks for publishing your code. Upon trying to run the code, I get the following error-
![image](https://user-images.githubusercontent.com/27413823/84298799-47fbbd80-ab82-11ea-842b-9ebbacc2d710.png)

I see that there is no function called 'get_inputs_desc' in model.py? How to make it work then? Could you please advise?

**Comment by Skylion007** [comment]
Seems like a Tensorpack version issue as it's defined in the basic model class. Make sure you are on the right version of Tensorpack.

**Comment by aasharma90** [comment]
I checked that I've tensorpack version 0.10.1
![image](https://user-images.githubusercontent.com/27413823/84299256-015a9300-ab83-11ea-8779-0c8f5b5f3623.png)

Does it mean I've to downgrade it to 0.8.9?

**Comment by Skylion007** [comment]
Yeah, you might need to then. I think the version tag was overwritten with a breaking bug fix if that 's the issue :/ . I think they renamed what is the inputs() function in model description. Most of the time overwriting GAN.py with the version in `examples/GAN/GAN.py` of Tensorpack you are using will solve the issue. If that doesn't work, just renaming `'inputs,` `build_graph,` etc to whatever they changed the API surface to will likely solve it.

Seems like I unfortunately made the mistake of solidifying the version right during a major refactor of Tensorpack. :/

Sorry for the inconvenience.

**Comment by aasharma90** [comment]
No worries @Skylion007 
Thanks a lot for your help, I used the version 0.8.9, and I'm past this error.
