### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by gxd1994** [brownvc/ganimorph#7]
Failed to run optimizer ArithmeticOptimizer, stage HoistCommonFactor. Error: Node LossA/GAN_loss/discrim/ArithmeticOptimizer/HoistCommonFactor_Add_loss is missing output properties at position :0 (num_outputs=0)

how can i fix it? thx

**Comment by Skylion007** [comment]
Hmm, interesting, I haven't seen this error before. What version of Tensorflow are you using?

**Comment by gxd1994** [comment]
tf 1.8

**Comment by gxd1994** [comment]
Can you recommend a version of tensorflow?

**Comment by Skylion007** [comment]
1.3.0 thought it worked on newer versions though. If it still persists let me know.

**Comment by gxd1994** [comment]
1.3 is ok, but 1.8 or hign will happen the same thing

**Comment by Joevin** [comment]
Me too, anybody has found the solution?

**Comment by l2009312042** [comment]
anybody has found the solution？

**Comment by Skylion007** [comment]
Running the old branch with Tensorflow 1.3 should have worked. I updated the repo just now to fix that bug.
